version: '2'

services:
  server:
    container_name: nexus-server
    image: sonatype/nexus3
    volumes:
      - ./volumes/nexus/data:/nexus-data
    ports:
      - 8081:8081
    networks:
      - service
      - openldap_service

networks:
  service:
  openldap_service:
    external: true
