version: '2'

services:
  server:
    container_name: gitea-server
    image: gitea/gitea
    links:
      - db:mysql
    volumes:
      - ./volumes/gitea/data:/data
    ports:
      - "${GITEA_SSH_PORT}:22"
      - "${GITEA_WEB_PORT}:3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${GITEA_HOSTNAME}
    networks:
      - openldap_service
      - service
      - backend

  db:
    container_name: gitea-db
    image: mysql:5.6
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend

networks:
  service:
  backend:
  openldap_service:
    external: true
