version: '2'

services:
  server:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - ./volumes/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
